### ISSUE TITLE
 Include Material sample in Bionomia

### ISSUE THREAD

**Issue by JCGiron** [bionomia/bionomia#110]
From SiB Colombia webinar:

Consider to include tissue collections where the basisOfRecord is MaterialSample.

**Comment by dshorthouse** [comment]
I have a suspicion that `recordedBy` or `identifiedBy` are not ordinarily populated with these, but I see no harm in adding it. Because the download from GBIF is a custom build for Bionomia, this will also require an update to code at GBIF's end, which means this may require 3-4 weeks to implement.

**Comment by dshorthouse** [comment]
Although closed, this won't come into effect until the next download & refresh of data in Bionomia from GBIF in ~ 1 week's time.
