### ISSUE TITLE
name not matched for J.R. McLintock

### ISSUE THREAD

**Issue by qgroom** [bionomia/bionomia#184]
I'm trying to assign this specimen to the collector John J.R. McLintock ([https://www.wikidata.org/wiki/Q108860143](https://www.wikidata.org/wiki/Q108860143))

He is present on Bionomia [https://bionomia.net/help-others/Q108860143/specimens](https://bionomia.net/help-others/Q108860143/specimens)

His agent string "J.R. McLintock" is on bionomia [https://bionomia.net/agent/2598791](https://bionomia.net/agent/2598791) as is the speciman.

However, the person has not matched with the name, so I have been unable to link it.

**Comment by qgroom** [comment]
Nevermind, I found the "make less exact box".

**Comment by dshorthouse** [comment]
What happened here is the scoring for J.J.R. McLintock vs. J.R. McLintock. All agent strings with the same last name are additionally scored via a processing queue when data are freshly downloaded from GBIF once every few weeks. Like so:

```
> require "dwc_agent"
> score = DwcAgent.similarity_score('J.J.R.', 'J.R.')
=> 0
```

The above _looks_ similar, but is functionally equivalent to:

```
> require "dwc_agent"
> score = DwcAgent.similarity_score('J.F.', 'J.B.')
=> 0
```

...where in most cases we'd want to assert that these agent strings represent two different people even though they share the same last name.

If I had to guess, John may have interchangeably used his two middle names as initials. One way around this is to add "J.R. McLintock" to the list of aka wikidata entries then refresh the wikidata data for John in Bionomia.

On a more personal note, by father was finishing his Ph.D. while McLintock was nearing retirement at the very same research station in Saskatoon, Saskatchewan where I was born. I'll have to ask if he remembers John.

**Comment by qgroom** [comment]
Thanks for the details, I wondered if the extra J was an issue. 

I'm currently working on the collectors of Montserrat and The Cayman Islands. Apparently McLintock was there once.  I can see the attraction during the winter! It is going to be an interesting analysis of collecting in the tropics,

**Comment by dshorthouse** [comment]
> I can see the attraction during the winter!
<img width="284" alt="Screen Shot 2022-01-15 at 4 13 20 PM" src="https://user-images.githubusercontent.com/326459/149637913-0d699c52-28ae-4160-84e1-c23298abdcca.png">
