### ISSUE TITLE
a wrinkle on "sort", "filter"

### ISSUE THREAD

**Issue by MargaretRDonald** [bionomia/bionomia#2]
Hi David,
I would find it immensely useful to filter or sort on institution code, as within an institution a common name string will often be unique to a particular collector, and one is often pretty safe in ascribing the specimen (collected) to that person.  
Cheers,
Margaret Donald

**Comment by dshorthouse** [comment]
Closing for now because we've also got #42 to track filter/sort but could reopen if necessary.
