### ISSUE TITLE
In the profile of a collector, show the Wikidata ID instead of the Wikidata URL

### ISSUE THREAD

**Issue by DavidFichtmueller** [bionomia/bionomia#254]
When looking at the profile of a collector, underneath the biographic information, the URL of the Wikidata item of the person is displayed (`https://www.wikidata.org/wiki/<Q-ID>`). 

![Bionomia_Profile_Wikidata](https://user-images.githubusercontent.com/7805030/217759176-ebd0c493-7d2d-44aa-b5c8-19def9afd723.png)

However that is different than the concept URI of the item (`http://www.wikidata.org/entity/<Q-ID>`, with "http" instead of "https" and "entity" instead of "wiki"). When using Wikidata as identifiers for person, the concept URIs should be used, so I would recommend changing the URL to the concept URI. When a user clicks the link in the browser, they are forwarded to the page, so for the users who just want to go on the page, it doesn't make a difference, but for those who want to copy the URI to note it as an identifier for the collector, it does make a difference.

**Comment by dshorthouse** [comment]
Good point. These are expressed at entity URIs in the JSON-LD exports & in the Frictionless Data downloads per dataset & it would be good to emphasize them as such for humans.
