### ISSUE TITLE
Preferred Language Error Issue

### ISSUE THREAD

**Issue by michaelbravothomas** [bionomia/bionomia#304]
Found a bug when adding Preferred Language (Choose your preferred language) in settings - When I select English the entry returns an error

Error
Sorry, we experienced an error.
![errorPreferredLanguage](https://github.com/bionomia/bionomia/assets/19720676/de2c270d-08a0-4787-b3e3-bf90ecff3d7a)

**Comment by dshorthouse** [comment]
That's a new one, thanks for reporting!

**Comment by dshorthouse** [comment]
I've been trying to reproduce this, but have failed to sort out where & how this happens. My suspicions is that there might have been a sequence of actions that had not yet completed just prior to having chosen a language. Is this a persistent, repeatable issue?

**Comment by dshorthouse** [comment]
Closing because cannot reproduce.
