### ISSUE TITLE
Can't "bulk attribute" when you make a string "less exact"

### ISSUE THREAD

**Issue by tmcelrath** [bionomia/bionomia#316]
So I've finished attributing "https://bionomia.net/Q100694962" but there are 1000s of records that can be attributed to this person when I make her agent strings "less exact". 

But I can't bulk download these to filter them easier. The bulk download includes nothing now. 

Basically, the filters I put on do not transfer over to Bulk Attributions.

**Comment by dshorthouse** [comment]
Yep...good point. I hadn't passed that parameter off to the csv download. Should be a quick fix and will investigate. Thanks for this.

**Comment by tmcelrath** [comment]
Thanks! Will test when live.

**Comment by dshorthouse** [comment]
Deployed! Not the greatest solution because the first 10k in a download is not necessarily what you first see in the UI. You'd persistently see the same 10k in a repeat download unless you explicitly flagged as "not them" and uploaded. So, I'd call it a half solution, requiring a more unified UI where download of candidate records happens in the same place rather than in a separate tab.

**Comment by abubelinha** [comment]
Not sure if this is related, but I am failing to download some CSVs for bulk attribution:
https://es.bionomia.net/help-others/0000-0002-8984-5899/candidates.csv
https://es.bionomia.net/help-others/0000-0002-8984-5899/candidates.csv?relaxed=1
https://es.bionomia.net/help-others/0000-0002-4436-9112/candidates.csv?relaxed=1

I am getting a network error, like if the remote file was not being generated when it is bigger.

The last one worked when I tried with less records (1694 KB size):
https://es.bionomia.net/help-others/0000-0002-4436-9112/candidates.csv

And other worked both relaxed and not (but the relaxed file was small: 534 KB).

Looks like some problem with bigger files.

**Comment by dshorthouse** [comment]
> Not sure if this is related, but I am failing to download some CSVs for bulk attribution: https://es.bionomia.net/help-others/0000-0002-8984-5899/candidates.csv https://es.bionomia.net/help-others/0000-0002-8984-5899/candidates.csv?relaxed=1 https://es.bionomia.net/help-others/0000-0002-4436-9112/candidates.csv?relaxed=1
> 
> I am getting a network error, like if the remote file was not being generated when it is bigger.
> 
> The last one worked when I tried with less records: https://es.bionomia.net/help-others/0000-0002-4436-9112/candidates.csv (BTW: this has 1694 KB filesize and contains 7667 rows, but [Bionomia announces it has 6426](https://es.bionomia.net/help-others/0000-0002-4436-9112?relaxed=0))
> 
> For other people IDs I tried, both downloads worked (but the relaxed file was small: i.e. 534 KB).
> 
> Looks like some problem with big files over some given size.
> 
> **EDIT:** I'd say the problem is at server side: I tried those downloads from different machines in different networks, using different Chrome versions.

This is unrelated, a silent casualty of a significant refactor that took place after this particular ticket. The issue here is a new bug that is presently loading records into memory rather than enumerating into the stream. Investigating a fix as I write this.
