### ISSUE TITLE
Deduping and linking ORCID iD and Wikidata profiles 

### ISSUE THREAD

**Issue by kcopas** [bionomia/bionomia#325]
I'm sure you've had to finagle this before @dshorthouse, but I stumbled across this pair of profiles that should really resolve to one and the same now, with the principal's passing in November 2021:
- [Jim Lowry](https://bionomia.net/help-others/0000-0003-0437-6753) (_ORCID iD-based_)
- [James K. Lowry](https://bionomia.net/help-others/Q21076181) (_Wikidata_)

**Comment by dshorthouse** [comment]
Got it. Thanks for this. Will have to run a deduping routine on Bionomia by cross-referencing ORCIDs against their wikidata entries. And then, I will figure out how Jim's two profiles slipped through. I see you just added his ORCID ID on wikidata & so the update routine on Bionomia *should* have caught this and merged the entries.
