### ISSUE TITLE
suggestions about metadata inside datapackage.json and Zenodo

### ISSUE THREAD

**Issue by abubelinha** [bionomia/bionomia#342]
Related to programmatic dataset downloads, I found some differences between Zenodo records/files api results and Frictionless datapackage.json content.  

Appart from naming differences (Zenodo-files vs Frictionless-resources), Zenodo file names are consistent with their urls.
But in datapackage.json they are not (see "-" inside names, instead of "_" used in "path" -and also in Zenodo for both concepts-).
Example from https://bionomia.net/dataset/e5e89b4d-bb7c-4dae-b1b4-924177e95c2b

- **zenodo (files) extract:**
"key": "**problem_collector_dates**.csv.zip",
"links": { "self": "https://zenodo.org/api/records/10875696/files/problem_collector_dates.csv.zip/content" },
"size": 233,
"checksum": "md5:b270f0b7019d44f29f6e2c38a186ecfb"

- **datapackage.json (resources) extract:**
"name": "**problem-collector-dates**",
"format": "csv",
"compression": "zip",
"path":"https://bionomia.net/dataset/e5e89b4d-bb7c-4dae-b1b4-924177e95c2b/problem_collector_dates.csv.zip",
"bytes": 233,
"hash": (not available yet)

#### Some suggestions:

1. Looking at other [frictionlessdata examples](https://specs.frictionlessdata.io/data-resource/#examples)) I know this is not mandatory, but wouldn't it make sense that "name" string matched the one used before file extension at the end of "path"?   
   I specifically mean not using different word separators ("-" vs "_").

2. Also interesting to include "hash" as md5 checksum (already mentioned in #341).

3. Would it be possible to somehow include Zenodo record link inside datapackage.json ?  (which permits to programatically access previous versions if anyone needs)

4. And the opposite: GBIF dataset UUID appears inside Zenodo "description", but perhaps Zenodo metadata system permits to use some other tags to provide easily readable links to the original dataset (I mean linking back from Zenodo to Bionomia dataset html page and/or datapackage.json url)

Regards
@abubelinha

**Comment by dshorthouse** [comment]
> 3\. Would it be possible to somehow include Zenodo record link inside datapackage.json ?  (which permits to programatically access previous versions if anyone needs)

Frictionless Data generation (makes static files, 2X a month) and pushing to Zenodo (monthly, so as not to flood) are independent processes, each using an asynchronous queue. I'd have to receive a response from Zenodo in the second processing routine & then write it back into datapackage.json, generated from the first routine that operates on a different schedule. This wouldn't work for a first upload to Zenodo, but it _could_ on subsequent uploads. The other hiccup here is that I see no appropriate key to include in the Frictionless Data metadata schema, https://datapackage.org/specifications/data-package/. I did include an undocumented `datasetKey` key here, but I'm a bit hesitant to to include yet more custom keys.

**Comment by dshorthouse** [comment]
2, 3, and 4 now implemented, but 1 will be skipped to maintain consistency with previous versions of files already submitted to Zenodo.
