### ISSUE TITLE
wrong Spanish familyName from Wikidata in users.csv.zip 

### ISSUE THREAD

**Issue by abubelinha** [bionomia/bionomia#344]
I suppose Bionomia somehow caches people data taken from Wikidata / ORCID.  A couple of questions about this:
- Is that info also reconstructed from those sources every two weeks?
- When constructing `users.csv.zip` file, how does Bionomia deal with languages which use several family names? 
  Spain: ([givenName](https://www.wikidata.org/wiki/Property:P735) + [familyName 1](https://www.wikidata.org/wiki/Property:P734) + [familyName 2](https://www.wikidata.org/wiki/Property:P1950))
  Wikidata: ([P735](https://www.wikidata.org/wiki/Property:P735) + [P734](https://www.wikidata.org/wiki/Property:P734) + [P1950](https://www.wikidata.org/wiki/Property:P1950))

I am sorting people attributed in our datasets by familyName + givenName.
But it turns out that `familyName` provided by Bionomia in `users.csv.zip` file is wrong for many Spanish people names, where [the last family name is not the preferred one](https://en.wikipedia.org/wiki/Spanish_naming_customs) (I think that is not the case for [Portuguese people names](https://en.wikipedia.org/wiki/Portuguese_name)).

I found one well constructed `familyName` from a Wikidata entry where both P734 & P1950 are available (which is not common).
But when P734 is missing Bionomia just takes the **last word of Wikidata item label** to construct `familyName`.  Am I right?
So I think this is just an issue with incomplete data sources (not with Bionomia).

Assuming all that, **I would improve Wikidata entries** (for the people I know) **providing P735+P734+P1950**, so Bionomia can  reconstruct `familyName` from P734 when it is available. 
Makes this sense? Would this reconstruction happen every two weeks?

Not sure how ORCID deals with this: I guess it has only one entry for familyName, so people put either one or both and Bionomia takes the full string into `familyName`, which is correct (I have not seen any wrong Spanish family names coming from ORCID in our datasets).

Thanks
@abubelinha

**Comment by dshorthouse** [comment]
Sorry about this. Bits from wikidata are gathered upon profile creation and occasionally refreshed, but this is not tied to Frictionless data exports. Here's the method used: https://github.com/bionomia/bionomia/blob/9c335a4c29512f686eb449b26fec3f5b9776eb22/lib/authorities/wikidata_search.rb#L450. You'll see an attempt here to make use of what's available and then fall back to parsing names when properties are missing. The logic here can no doubt be refined. Can you please provide an example?

**Comment by abubelinha** [comment]
> Bits from wikidata are gathered upon profile creation and occasionally refreshed, but this is not tied to Frictionless data exports.

So you mean it's better to occasionally report here a big list of wikidata IDs which I suggest to be refreshed?
No problem at all.

> Can you please provide an example?

If you mean an example of wrong familyName in users.csv.zip, I had already corrected all wikidata entries I found in my concerned datasets. 
But it's easy to find more in other datasets:
[Q5359097](https://bionomia.net/Q5359097) `firstName` should be "Paunero" but if you download frictionless data from [835613da-f762-11e1-a439-00145eb45e9a](https://bionomia.net/dataset/835613da-f762-11e1-a439-00145eb45e9a?page=4) you will see her `firstName` is reported as "Ruiz".

Fortunately Bionomia pages header is using the full wikidata label (which contains her full name string "**Elena Paunero Ruiz**"). 
But if you play attention to her wikidata aliases shown below ("Paunero; E. Paunero; E. Paunero Ruiz"), nobody calls her "Ruiz" which, according to `users.csv.zip`/`firstName`, would be the most common version she used i.e. when signing articles, labels, etc
It was not "Ruiz" but "Paunero" (which is also her IPNI abbreviation):
https://en.wikipedia.org/wiki/Elena_Paunero_Ruiz#Publications

**Comment by abubelinha** [comment]
Something to add before you answer about this:

> So you mean it's better to occasionally report here a big list of wikidata IDs which I suggest to be refreshed?
No problem at all.

Actually I already corrected several wikidata entries during the last couple of years but did not annotate them.
It would be easier if I fuzzy merge our dataset persons names against a full list of person names in Bionomia.
I guess [bionomia-public-profiles.csv](https://bionomia.net/data/bionomia-public-profiles.csv) is the file to use, right?

Should I also report entries not present in that file?

I am also interested in searching wikidata / ORCID ids for other names in our dataset.
What does actually the [api.bionomia.net/user.json](https://api.bionomia.net/user.json?q=R.%20%C3%81lvarez&limit=5) search do?  
Is it just matching queries against the above file, or is it live-searching wikidata/orcid apis?

I believe it is a live-search since it returns entries (both orcid & wikidata) which are not in the above file.
But why doesn't it return some names which exactly match the full string name shown in ORCID?
 (i.e. [this search response](https://api.bionomia.net/user.json?q=Miguel%20Serrano) does not contain [this ORCID](https://orcid.org/0000-0003-3079-2355))

I am also surprised about some matches containing "score" values higher than 100. 
Is there any known scoring scale (with a maximum possible value)?

**Comment by dshorthouse** [comment]
> So you mean it's better to occasionally report here a big list of wikidata IDs which I suggest to be refreshed? No problem at all.

For what it's worth, Bionomia executes a scheduled SPARQL to find wikidata items with a Bionomia ID (P6944) that have been recently edited and executes a refresh. When logged in to Bionomia, there's also a "Refresh wikidata" utility under each profile.
  
> If you mean an example of wrong familyName in users.csv.zip, I had already corrected all wikidata entries I found in my concerned datasets. But it's easy to find more in other datasets: [Q5359097](https://bionomia.net/Q5359097) `firstName` should be "Paunero" but if you download frictionless data from [835613da-f762-11e1-a439-00145eb45e9a](https://bionomia.net/dataset/835613da-f762-11e1-a439-00145eb45e9a?page=4) you will see her `firstName` is reported as "Ruiz".

Hmm. Any chance you might be misinterpreting the http://schema.org/familyName as `firstName`? There's no field in users.csv for `firstName`, but there is a http://schema.org/givenName. In any case, the above example is one where P734 is absent and so Bionomia falls back to parsing the label.
 
> Fortunately Bionomia pages header is using the full wikidata label (which contains her full name string "**Elena Paunero Ruiz**"). But if you play attention to her wikidata aliases shown below ("Paunero; E. Paunero; E. Paunero Ruiz"), nobody calls her "Ruiz" which, according to `users.csv.zip`/`firstName`, would be the most common version she used i.e. when signing articles, labels, etc It was not "Ruiz" but "Paunero" (which is also her IPNI abbreviation): https://en.wikipedia.org/wiki/Elena_Paunero_Ruiz#Publications

If you include a value for P734 and adjust P735 as you see fit, Bionomia won't parse the label to interpret a value for http://schema.org/familyName. However, all the `en` aliases are used in search for & linking of candidate specimen records in Bionomia, which is the ultimate aim.

**Comment by dshorthouse** [comment]
> * I guess [bionomia-public-profiles.csv](https://bionomia.net/data/bionomia-public-profiles.csv) is the file to use, right?

Not sure how well that would work for your puposes because it is indeed lacking profiles that have not been made public in Bionomia, but you could try.

> * Should I also report entries I corrected but not present in that file?

Are you sharing these to GBIF via `recordedByID` or `identifiedByID`? Bionomia will pick these up. If not, sure, I can bulk import some wikidata items (provided there's a date of death or a date of birth >= 120 years ago). You can also add them yourself via https://bionomia.net/help-others/add when logged in.
 
> I am also interested in searching wikidata / ORCID ids for other names in our dataset. What does actually the [api.bionomia.net/user.json](https://api.bionomia.net/user.json?q=R.%20%C3%81lvarez&limit=5) search do? Is it just matching queries **against the above file**, or is it **live-searching wikidata/orcid apis**?

It uses Elasticsearch behind the scenes that had been populated from values once pulled from both wikidata and ORCID. Both of these are periodically refreshed, wikidata more often because there's no effective way to query ORCID for "what's changed" as there is with wikidata. There are no live queries to wikidata and ORCID; what you see are cached values. Here's what the query looks like: https://github.com/bionomia/bionomia-api/blob/master/helpers/queries.rb#L35. Results returned include both profiles made public and not in Bionomia, but there are additional parameters if you wish to filter the response.
 
> * YES (live), it returns entries (both orcid & wikidata) which are not in the above file ... but:
> * NO: it doesn't return some names which exactly match the full string name shown in ORCID
>   (i.e. [this search response](https://api.bionomia.net/user.json?q=Miguel%20Serrano) does not contain [this ORCID](https://orcid.org/0000-0003-3079-2355))

That person did not exist in Bionomia, but I've since added him. But, you are correct in that exact match (if there is in fact a profile whose name could match exactly) is not an easy thing to do with Elasticsearch. The only field that might truly participate in an exact match is the label (not the parts of names), but even so, the outcome is often unsatisfactory. 

> * NO: after a wikidata edition (i.e. [P734 info added](https://www.wikidata.org/wiki/Q21507062)), Bionomia api keeps [returning same "family" info](https://api.bionomia.net/user.json?q=Bartolom%C3%A9%20Casaseca%20Mena&limit=1); doesn't look like a cached query because if I change the query string [a little bit](https://api.bionomia.net/user.json?q=Bartolom%C3%A9%20Casaseca&limit=1), same person is returned for the first entry (but still with old wikidata info).

That one did not have a Bionomia ID, P6944 on it so Bionomia was unaware of a merge event; it periodically executes a SPARQL against wikidata, looking for all items with P6944 to find those that have been merged. What you're looking at is Q87652185 that has since been merged with Q21507062. These have all been tidied up now.

>   Just in case, I looked at other non-redirected items with P734 added and I see no consistence (sometimes api returns correct "family" like it is in wikidata, sometimes it doesn't). Might this depend on person having already been attributed in Bionomia, I don't know.

This is probably an artifact of parsing the label when P734 is not populated.
 
> So I am not sure: where does the info come from when I call this api? Less important: is the scoring system explained somewhere? (I expected "best" matches to score 100, but I see higher values sometimes)

If I understood correctly, the Elasticsearch score is relative, not absolute; that is, its value depends on the pool of candidate hits, which of course is a moving target. And, it's also based on the weighting of various name parts as shown in that query. I've neglected this part of the response, just letting Elasticsearch do its thing. But, I agree it should be revisited because any tweak to the logic in the query has a knock-on effect on the score. A client of the API might have hard-coded decisions based on ranges of score values, which is actually not how these ought to be used. It's more like, "Of all these X hits returned, this one is the best match." It's closer to a rank than it is an absolute metric.

**Comment by abubelinha** [comment]
> Hmm. Any chance you might be misinterpreting the http://schema.org/familyName as `firstName`

Sorry, yes, I was indeed meaning `familyName` (which should be the first one -when two are available- in Spanish names).

> For what it's worth, Bionomia executes a scheduled SPARQL to find wikidata items with a Bionomia ID (P6944) that have been recently edited and executes a refresh. When logged in to Bionomia, there's also a "Refresh wikidata" utility under each profile. (...) You can also add them yourself via https://bionomia.net/help-others/add when logged in.

So great!  Thanks a lot for explaining. 

Thanks a lot also for clarifications on how API works.
So API won't ever return people which are not yet in Bionomia (either with public or hidden profiles), right?

Just a final clarification:  is it possible that a wikidata-based profile is not public? (so not shown in [bionomia-public-profiles.csv](https://bionomia.net/data/bionomia-public-profiles.csv)).
I'd say "no, all must be public and visible in that file" because Bionomia only uses wikidata for dead people.
Unless somebody with an ORCID and hidden profile dies and then ... what will do Bionomia?  Keep it hidden or not?

**Comment by dshorthouse** [comment]
> So API won't ever return people which are not yet in Bionomia (either with public or hidden profiles), right?

That's correct. 

> Just a final clarification:  is it possible that a wikidata-based profile is not public? (so not shown in [bionomia-public-profiles.csv](https://bionomia.net/data/bionomia-public-profiles.csv)).

Yes, that too is possible. A number of them had been bulk imported, but may not have ever collected/determiner specimens. There some cruft. It's up to an attributor "scribe" to make these wikidata-based profiles public. However, if a wikidata-based profile is new to Bionomia and came through resolving recordedByID/identifedByID, these ones are made public without human action.

> I'd say "no, all must be public and visible in that file" because Bionomia only uses wikidata for dead people.
> 
> Unless somebody with an ORCID and hidden profile dies and then ... what will do Bionomia?  Keep it hidden or not?

It's auto-converted to a wikidata-based profile, but remains hidden until a human makes it public.

**Comment by abubelinha** [comment]
> You can also add them yourself via https://bionomia.net/help-others/add when logged in.

After trying it I understand that not only ads but it also upgrades IDs (i.e., a wikidata entry which I have just added birth/death dates, P734 or whatever).
That's so handy since I'd like to add some collectors' IDs (that I know not to be yet in GBIF) to be available in API for other Bionomia's potential users.

A possible enhancement I suggest is letting the interface pass either one ID or a separated list of IDs, so we can upgrade many of them at once. So we avoid [filling inputbox+clicking 'Add'+waiting for page reload] 30 times.

**Comment by dshorthouse** [comment]
Added [P1950](https://www.wikidata.org/wiki/Property:P1950) to the `wiki_user_data` method. Will make a new ticket to convert input to textatea for adding/updating.
