### ISSUE TITLE
As a researcher I would like to use CITATION.cff file to cite Bionomia

### ISSUE THREAD

**Issue by dimus** [bionomia/bionomia#392]
It would be nice to have a CITATION.cff file for Bionomia

https://github.com/citation-file-format/citation-file-format/blob/main/README.md

Such file is recognized by Zenodo, and GitHub creates APA and Bibtex citations from its content.

for example:

![image](https://github.com/user-attachments/assets/68f5beb8-354e-4114-9b41-a5f34a832c2a)

**Comment by dshorthouse** [comment]
Thanks for this. Created a bare-bones file.
