### ISSUE TITLE
sort

### ISSUE THREAD

**Issue by watkinsg12** [bionomia/bionomia#42]
Is there any way to sort the list of found records so that I could more easily determine things that are not the right person simply by looking at the collection year?  sorting by collector or determiner column would also be amazing.

**Comment by dshorthouse** [comment]
I would very much like to do this, but it's a question of indexing on columns and that translates directly to more memory on the cloud server & sadly, that requires more money. A similar request is #12. As a compromise, one way to make this possible is to download as a csv file and then do the sorting/filtering in a spreadsheet then upload the claims. It's not as pleasing and immediate, but at least is more performant.
