### ISSUE TITLE
"not me" button should be "not them" when helping others

### ISSUE THREAD

**Issue by onco-p53** [bionomia/bionomia#50]
When helping others e.g.: https://bionomia.net/help-others/Q22113468 the button to indicate that specimens were not associated with a person should read "not them" rather than "not me"

<img width="1119" alt="bionomia not me bug" src="https://user-images.githubusercontent.com/18092365/92364610-6e140800-f147-11ea-9d92-00322351b120.PNG">

**Comment by dshorthouse** [comment]
Good point! I'm reusing bits and pieces throughout the site to minimize the codebase, but this one doesn't make sense.
