### ISSUE TITLE
wrong dates

### ISSUE THREAD

**Issue by ejmarcano** [bionomia/bionomia#62]
page https://bionomia.net/Q5850623  shows the wrong date of birth of Eugenio de Jesús Marcano Fondeur.  It should be September 18, 2003.

**Comment by dshorthouse** [comment]
Thanks for pointing that out! These data come from Wikidata and once edited there, can be refreshed in Bionomia. I've just done that now and we're all good to go. Anyone logged into Bionomia with their ORCID credentials can do this too.
