### ISSUE TITLE
Allow filter by Kingdom

### ISSUE THREAD

**Issue by dshorthouse** [bionomia/bionomia#63]
As @JCGiron points out in #56 & as in the subject.

**Comment by dagendresen** [comment]
Kingdom (and maybe, if not to expensive, something in between such as phylum) also in the bulk download would also be useful.

**Comment by dshorthouse** [comment]
Some moving parts here at GBIF's end so made a pull request to at least add Kingdom https://github.com/gbif/occurrence/pull/240
