### ISSUE TITLE
API requests return forbidden

### ISSUE THREAD

**Issue by MortenHofft** [bionomia/bionomia#67]
https://api.bionomia.net/user.json?q=Jan%20John returns 403 forbidden
This is new since yesterday

**Comment by dshorthouse** [comment]
Interesting. Is this consistent? Am not getting this now and am wondering if perhaps there is a certificate or session issue here with https://bionomia.net vs. https://api.bionomia.net.

**Comment by MortenHofft** [comment]
Still 403 for me. But turns out it is only in chrome.

Works for me in Safari, Firefox and when using chrome in incognito mode.
Disabling cache doesn't help and I do not see any cookies to clear. Odd.

**Comment by MortenHofft** [comment]
Found it - it is the referer header when clicking the link in Github.

```
curl 'https://api.bionomia.net/user.json?q=Jan%20John' \
  -H 'Referer: https://github.com/bionomia/bionomia/issues/67'
```

**Comment by dshorthouse** [comment]
Aha! Thanks for sleuthing. Sounds like I have a certificate problem them.

**Comment by dshorthouse** [comment]
OK, I figured out that this something going on with CORS and/or some new security policy in Chrome and Firefox not present in Brave. Will have to dig some more in how to fix this.
