### ISSUE TITLE
Allow to click on person's name in 'Help view' to go back to 'profile overview'

### ISSUE THREAD

**Issue by JCGiron** [bionomia/bionomia#91]
It would be nice to be able to go back to the general overview of someone's profile from the page where one is attributing specimens, by simply clicking on the person's name.

**Comment by dshorthouse** [comment]
There are a couple things going on here & maybe it could be made more obvious for everyone. Here's the complication:

When a profile is not yet public, whatever is shown in its "public" overview page won't be very pleasing...just some numbers in a tiny panel, mostly as a placeholder to indicate that the profile is hidden (eg https://bionomia.net/0000-0002-5166-809X). In this case, a link from the helping interface would probably be uninformative. Anyone can make a wikidata profile public within that helping interface but only an ORCID account-owner can make their own profile public from their own account. And of course, anyone can attribute specimens to anyone else, ORCID accounts included. So, all these scenarios combined needed something a bit more extensive than clicking a linked name. Currently, this is coordinated with a series of links well under the names with icons like "Yes, make public" for the wikidata accounts (not present in the ORCID ones) and when actually already made public both wikidata and ORCID accounts have links, "Public Profile".

Is there's a better way to do all the above? Should we add a link to a person's name when it's public & then not have it when not public? Or, should we add a link to a name to the public version regardless of whether the profile has actually been made public?

**Comment by dshorthouse** [comment]
Another thought. Maybe add a lock icon to the helping page for an ORCID profile that's not yet been made public so it's a bit more obvious?

**Comment by JCGiron** [comment]
It was for me more of a practical thing:
I was assigning specimens to several Latin American researchers and went through several pages of discovered specimens. I wanted to go back and check how many specimens I had assigned. So going to the previous page took several clicks, then go back to the general Help page to try to find this particular profile again... So I kept trying to click just on the name to go directly to the overview page, but, of course, nothing happened.

I also, found myself wanting to find the search button from the help view instead of hving to go to the home page to find it...

**Comment by JCGiron** [comment]
Regarding ORCID account-owners, what if there was an option in ORCID for Biology-related fileds, to make their Bionomia profile public if the profile is ever created...

**Comment by dshorthouse** [comment]
Aha, this as a lot more than just an icon ;)~

There's a drop-down beside your picture in the top menu bar with a link there, People Helped /  Personas ayudadas. That page will show all the people you helped with numbers you attributed, ordered by most recent first. Does that help a bit? I concede though that there is a lot of back & forth and lot of clickiness. Should we add search to the top panel of a profile page when in the helping interface?

**Comment by dshorthouse** [comment]
> Regarding ORCID account-owners, what if there was an option in ORCID for Biology-related fileds, to make their Bionomia profile public if the profile is ever created...

I think we're better off leaving this up to the ORCID account holder as cumbersome as this might be for us making attributions on their behalf. An argument could be made that when someone deposits specimens at a museum/collection the data will be made publicly available. However, it's entirely possible that they would not have anticipated that their specimen data would be presented in this way.

**Comment by JCGiron** [comment]
> Aha, this as a lot more than just an icon ;)~
> 
> There's a drop-down beside your picture in the top menu bar with a link there, People Helped / Personas ayudadas. That page will show all the people you helped with numbers you attributed, ordered by most recent first. Does that help a bit? I concede though that there is a lot of back & forth and lot of clickiness. Should we add search to the top panel of a profile page when in the helping interface?

Yes, that helps. I have seen that view before... it didn't iccur to me to go there.

And I vote yes to add search to the helping interface.
